### ISSUE TITLE
ROSCO Debug output shows some NaNs and Infitities with run_DLC.py test

### ISSUE THREAD

**Issue by yonghoonlee** [WISDEM/WEIS#18]
I tested with the run_DLC.py from example/aeroelasticse folder.

For DLC 6.1 and 6.3, some of the ROSCO debug output variables show NaNs and Infinities in RO.dbg files.
I am not sure if these are anticipated output (since they are extreme wind speed cases), or simulation failures.

Also, could you confirm if it is right method to run testing script following way:

`mpirun -n 8 python run_DLC.py`

I was a bit concerned if it is running duplicated scripts for creating 8 identical simulations, since the computation time did not significantly reduced even with 8 threads.

**Comment by gbarter** [comment]
@nikhar-abbas or @dzalkind or @ptrbortolotti may be able to help.

**Comment by dzalkind** [comment]
Hi @yonghoonlee, I would expect to see some NaNs or Infinities in the RO.dbg files for parked cases because the wind speed estimator in ROSCO isn't set up to estimate the wind speed reliably in these cases.  Fortunately, it's not affecting the controller during these cases, so we'll probably leave this as it is in ROSCO until it does.

We use MPI to run on several nodes of a supercomputer, but locally you might want to try running with multiprocessing; an example is in `examples/run_general.py`

**Comment by yonghoonlee** [comment]
@dzalkind Thank you for your answers. For us I believe MPI may be useful for our high performance computer system. However, I will also look into the run_general.py for the multiprocessing first, and close this issue. Thank you.
