### ISSUE TITLE
Bug / Typo in gc_PoseOptimization.py

### ISSUE THREAD

**Issue by damien-castaignet** [WISDEM/WEIS#234]
Small bug / typo in gc_PosOptimization: https://github.com/WISDEM/WEIS/blob/e5e124c7e2340f4392127ba40f256486d5f97d40/weis/glue_code/gc_PoseOptimization.py#L122

I believe that 
> upper=control_opt['servo']['torque_control']['zeta_max'])

should be 
> upper=control_opt['servo']['torque_control']['zeta']['max'])

**Comment by dzalkind** [comment]
Thanks for catching this, Damien!

We're getting read to re-start development here and this looks like a quick fix.

Best, Dan

**Comment by mlidGWT** [comment]
Hello, I don't know if this is a related issue, but I am also getting an error with `gc_PosOptimization`, but related to line 390:
>  File "/Users/meglidrbauch/Software/WEIS/weis/glue_code/gc_PoseOptimization.py", line 390, in set_initial_weis
    wt_opt["tcons_post.max_allowable_td_ratio"] = blade_constr["tip_deflection"]["margin"]
  File "/Users/meglidrbauch/miniconda3/envs/weis-env/lib/python3.10/site-packages/openmdao/core/problem.py", line 513, in __setitem__
    self.set_val(name, value)
  File "/Users/meglidrbauch/miniconda3/envs/weis-env/lib/python3.10/site-packages/openmdao/core/problem.py", line 544, in set_val
    self.model.set_val(name, val, units=units, indices=indices)
  File "/Users/meglidrbauch/miniconda3/envs/weis-env/lib/python3.10/site-packages/openmdao/core/system.py", line 5368, in set_val
    raise KeyError(f'{model.msginfo}: Variable "{name}" not found.')
KeyError: '<model> <class WindPark>: Variable "tcons_post.max_allowable_td_ratio" not found.'

I am trying to run WEIS in the style of Example 02 where I specify an openfast directory, and have been troubleshooting various errors until this point, but this one has me stumped since it seems to go into my environment's python files. For reference, example_02 did execute successfully for me on my local installation, but as far as I can tell all of my input files are setup correctly for what I'm trying to do. 

The preceding lines to the error above are:
>Loading wind turbine data for NREL's ROSCO tuning and simulation processeses
>-----------------------------------------------------------------------------
>Loading FAST model: IEA-15-240-RWT-GWTBaseline.fst 
>Loading rotor performace data from text file: >/Users/meglidrbauch/Software/LoadsRuns/SimulationLibrary/6011_SBIR/L14_InputFiles/IEA15_GWTB_Cp_Ct_Cq.txt
>Traceback (most recent call last):
 >> File "/Users/meglidrbauch/Software/LoadsRuns/SimulationLibrary/6011_SBIR/weis_driver.py", line 15, in <module>
    wt_opt, modeling_options, opt_options = run_weis(fname_wt_input, fname_modeling_options, fname_analysis_options)
  File "/Users/meglidrbauch/Software/WEIS/weis/glue_code/runWEIS.py", line 161, in run_weis
    wt_opt = myopt.set_initial_weis(wt_opt)
  File "/Users/meglidrbauch/Software/WEIS/weis/glue_code/gc_PoseOptimization.py", line 390, in set_initial_weis
    wt_opt["tcons_post.max_allowable_td_ratio"] = blade_constr["tip_deflection"]["margin"]

**Comment by dzalkind** [comment]
Hi Meg,

I'm sorry this issue is a bit stale.  I'm not sure the issues are related.  If you're still having issues with your example, can you post to a new issue with your exact configuration?

Best, Dan
